# Generated by Django 6.1.1 on 2026-09-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('length', models.IntegerField()),
                ('entropy_bits', models.FloatField()),
                ('breach_count', models.IntegerField(default=0)),
            ],
        ),
    ]
